version: "3.7"
services:
  web-server:
    container_name: web-server
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
    networks:
      - mynetwork
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5001:80"
    networks:
      - mynetwork

networks:
  mynetwork:
volumes:
  mysql-data:
